{{ if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "spot-config-webhook.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-delegator-{{ template "spot-config-webhook.fullname" . }}-default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "spot-config-webhook.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  name: {{ template "spot-config-webhook.fullname" . }}-apiext
  namespace: kube-system
rules:
- apiGroups:
  - {{ .Values.apiService.group }}
  resources:
  - {{ template "spot-config-webhook.fullname" . }}
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - secrets
  - configmaps
  - serviceaccounts
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: extension-{{ template "spot-config-webhook.fullname" . }}-authentication-reader-default
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "spot-config-webhook.fullname" . }}-apiext
subjects:
- kind: ServiceAccount
  name: {{ template "spot-config-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "spot-config-webhook.fullname" . }}-unauth-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:unauthenticated
---
{{ if .Values.rbac.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ template "spot-config-webhook.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: psp:{{ template "spot-config-webhook.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "spot-config-webhook.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "spot-config-webhook.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.spot-config-webhook
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{ end }}
{{ end }}
