{{- if and .Values.traefik.rbac.enabled .Values.traefik.rbac.psp.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ template "pipeline-cluster-ingress.saname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: psp:{{ template "pipeline-cluster-ingress.saname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "pipeline-cluster-ingress.saname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "pipeline-cluster-ingress.saname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.{{ template "pipeline-cluster-ingress.saname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
