apiVersion: v1
name: spark-shuffle
version: 0.0.5
description: A Helm chart for Spark Shuffle in Kubernetes
home: https://banzaicloud.com
sources:
  - https://github.com/banzaicloud/spark
keywords:
- spark
- shuffle
maintainers:
- name: Banzai Cloud
  email: info@banzaicloud.com
