version: 2.1

orbs:
  helm: banzaicloud/helm@0.0.8

executors:
  helm311:
    docker:
      - image: ghcr.io/banzaicloud/helm:0.0.7

helm-repositories: &helm_repositories
  - run: helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master
  - run: helm repo add rimusz https://charts.rimusz.net

workflows:
  version: 2
  static-checks:
    jobs:
      - helm/lint-chart:
          name: Lint (Helm 3)
          executor: helm311
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - helm/publish-chart:
          context: helm
          executor: helm311
          charts-dir: '.'
          add-extra-repositories: *helm_repositories
          filters:
            tags:
              only: /\S+\/\d+.\d+.\d+(?:-(?:dev|rc|banzai)\.\d+)?/
            branches:
              ignore: /.*/
