{{ if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "spot-scheduler.fullname" . }}
  labels:
    app: {{ template "spot-scheduler.name" . }}
    chart: {{ template "spot-scheduler.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "spot-scheduler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "spot-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler

{{ if .Values.rbac.psp.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ template "spot-scheduler.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: psp:{{ template "spot-scheduler.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "spot-scheduler.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "spot-scheduler.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - psp.{{ template "spot-scheduler.fullname" . }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{ end }}
{{ end }}
