apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "prometheus-operator.fullname" . }}
  labels:
{{ include "prometheus-operator.labels" . | indent 4 }}
rules:
- apiGroups:
{{- if .Values.prometheusOperator.customResourceGroupRemap.enabled }}
  - {{ .Values.prometheusOperator.customResourceGroupRemap.newGroup }}
{{- else }}
  - monitoring.coreos.com
{{- end  }}
  resources:
  - alertmanagers
  - alertmanagerconfigs
  - prometheuses
  - thanosrulers
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
