apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "prometheus-operator.labels" . | indent 4 }}
imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 2 }}
