apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-secrets-init.fullname" . }}
  labels:
    {{- include "kube-secrets-init.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kube-secrets-init.selectorLabels" . | nindent 4 }}

{{- if .Values.telemetry.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-secrets-init.componentname" (list . "telemetry") }}
  labels:
    {{- include "kube-secrets-init.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: telemetry
      protocol: TCP
      name: telemetry
  selector:
    {{- include "kube-secrets-init.selectorLabels" . | nindent 4 }}
{{- end }}
