{{- if and .Values.telemetry.enabled .Values.telemetry.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-secrets-init.fullname" . }}
  labels:
    {{- include "kube-secrets-init.labels" . | nindent 4 }}
  {{- with .Values.telemetry.serviceMonitor.additionalLabels }}
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.telemetry.serviceMonitor.interval }}
      port: telemetry
    {{- with .Values.telemetry.serviceMonitor.relabellings }}
      metricrelabelings:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  jobLabel: {{ include "kube-secrets-init.fullname" . }}
  selector:
    matchLabels:
      {{- include "kube-secrets-init.selectorLabels" . | nindent 6 }}
{{- end }}
