server:
  config:
    persistence:
      default:
        driver: "cassandra"

        cassandra:
          hosts: "cassandra-0.cassandra"
          port: 9042
          keyspace: "cadence"
          consistency: "One"

          # Authentication
          # user: ""
          # password: ""

      visibility:
        driver: "cassandra"

        cassandra:
          hosts: "cassandra-0.cassandra"
          port: 9042
          keyspace: "cadence_visibility"
          consistency: "One"

          # Authentication
          # user: ""
          # password: ""

cassandra:
  enabled: false
